name: Publish Release Candidate Docker Image

on:
  workflow_dispatch:
    inputs:
      rc_tag:
        description: Tag da imagem RC
        required: true
        default: rc-manual

env:
  FULL_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME != '' && vars.DOCKER_IMAGE_NAME || 'malacration/dealerlenium' }}

permissions:
  contents: read

jobs:
  push_rc_to_registry:
    name: Build and Push RC Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for RC image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.FULL_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.rc_tag }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
